// riml-ds の tools/lint/stylelint.config.js を土台にした、サイト側の CSS 規約。
// 生値禁止・論理プロパティのみ・モーションは prefers-reduced-motion の中だけ、は同じ。
// 違うのは 2 点だけ:
//   1. サイト固有の CSS 変数に --riml-* を許す（--rd-* はデザインシステムの持ち物）
//   2. CSS Modules のローカルクラスを許すため selector-class-pattern を緩める
const colorKeywords = [
  'inherit',
  'currentColor',
  'currentcolor',
  'transparent',
  'Canvas',
  'CanvasText',
  'LinkText',
  'VisitedText',
  'ActiveText',
  'ButtonFace',
  'ButtonText',
  'ButtonBorder',
  'Field',
  'FieldText',
  'Highlight',
  'HighlightText',
  'SelectedItem',
  'SelectedItemText',
  'Mark',
  'MarkText',
  'GrayText',
  'AccentColor',
  'AccentColorText',
]

/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard'],
  plugins: [
    'stylelint-declaration-strict-value',
    './vendor/riml-ds/tools/lint/stylelint-plugin/index.js',
  ],
  rules: {
    'scale-unlimited/declaration-strict-value': [
      [
        '/color$/',
        'fill',
        'stroke',
        'background',
        'background-color',
        'border',
        'border-color',
        'outline-color',
        'box-shadow',
        'font-family',
        'font-size',
        'font-weight',
        'line-height',
        'border-radius',
        'z-index',
        'transition-duration',
        'animation-duration',
        'transition-timing-function',
        'animation-timing-function',
        '/^(padding|margin|gap|inset)/',
        'inline-size',
        'block-size',
        'min-inline-size',
        'min-block-size',
        'max-inline-size',
        'max-block-size',
      ],
      {
        ignoreValues: {
          '': [
            'inherit',
            'initial',
            'unset',
            'revert',
            'revert-layer',
            'currentColor',
            'transparent',
            'none',
            'auto',
            '0',
            '100%',
            'fit-content',
            'max-content',
            'min-content',
            '1px',
            '-1px',
            '100dvb',
            '100dvi',
            '100cqi',
            '100cqb',
          ],
          '/color$/': colorKeywords,
          background: colorKeywords,
          'background-color': colorKeywords,
          border: colorKeywords,
          'border-color': colorKeywords,
          'outline-color': colorKeywords,
          'box-shadow': colorKeywords,
          fill: colorKeywords,
          stroke: colorKeywords,
          'font-weight': ['inherit', 'bolder', 'lighter'],
          // スクロール駆動のアニメーションは進行をスクロール量に一致させる必要が
          // あるので linear 固定。イージングのトークンを当てると対応がずれる
          'animation-timing-function': ['linear', 'inherit'],
          'z-index': ['auto', '-1', '0', '1'],
          'line-height': ['normal', 'inherit', '1'],
          '/^(padding|margin|gap|inset)/': ['auto', '0', 'inherit'],
        },
        ignoreFunctions: true,
        expandShorthand: true,
      },
    ],
    // riml-ds は text-align も禁止しているが、あれは部品のための規約。
    // ランディングページは中央揃えの段落が要るので、物理プロパティだけを禁止する。
    'property-disallowed-list': [
      'margin-left',
      'margin-right',
      'padding-left',
      'padding-right',
      'border-left',
      'border-right',
      'left',
      'right',
      'float',
      'width',
      'height',
      'min-width',
      'min-height',
      'max-width',
      'max-height',
    ],
    'unit-disallowed-list': [
      ['px'],
      {
        ignoreProperties: {
          px: [
            'outline-width',
            'outline-offset',
            'outline',
            'border',
            'border-width',
            'border-block',
            'border-block-start',
            'border-block-end',
            'border-inline',
            'border-inline-start',
            'border-inline-end',
          ],
        },
      },
    ],
    'selector-max-id': 0,
    // riml-ds は 0,3,0。こちらは CSS Modules で 1 ファイルに閉じているので、
    // ファイルをまたぐ詳細度の殴り合いが起こらない。代わりに :checked からの
    // 兄弟セレクタ（JS 無しで状態を表す）が要るので 0,5,0 まで許す。
    'selector-max-specificity': '0,5,0',
    'declaration-no-important': true,
    'media-feature-range-notation': 'context',
    'color-function-notation': 'modern',
    'color-no-hex': true,
    'custom-property-pattern': [
      '^(rd|riml)-[a-z0-9-]+$',
      { message: 'CSS 変数は --rd-（デザインシステム）か --riml-（サイト固有）で始める' },
    ],
    'selector-class-pattern': null,
    'no-descending-specificity': null,
    'import-notation': 'string',
    'riml-ds/motion-in-media': true,
    'riml-ds/baseline-newly-needs-supports': true,
    'riml-ds/no-palette-token': true,
  },
  ignoreFiles: [
    '**/node_modules/**',
    '**/.next/**',
    '**/out/**',
    'vendor/**',
    'src/styles/generated/**',
    '**/storybook-static/**',
  ],
}
